name: CMake CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        include:
          # GCC Debug
          - os: ubuntu-latest
            build_type: Debug
            cc: gcc
            cxx: g++

          # GCC Release
          - os: ubuntu-latest
            build_type: Release
            cc: gcc
            cxx: g++

          # Clang Debug
          - os: ubuntu-latest
            build_type: Debug
            cc: clang
            cxx: clang++

          # Clang Release
          - os: ubuntu-latest
            build_type: Release
            cc: clang
            cxx: clang++

    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install dependencies
      run: |
        sudo apt update

        sudo apt install -y \
          wget \
          gnupg \
          software-properties-common \
          cmake \
          ninja-build \
          build-essential \
          clang \
          libglfw3-dev \
          xorg-dev

        sudo apt update

    - name: Setup Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.0
      with:
        vulkan-query-version: 1.3.275.0
    - name: Verify Vulkan tools
      run: |
        which glslc
        glslc --version
        vulkaninfo --summary || true

    - name: Configure CMake
      run: |
        cmake -B build \
          -G Ninja \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -S .

    - name: Build
      run: |
        cmake --build build

    - name: List build output
      run: |
        ls -R build